### ISSUE TITLE
Running list of 2019 file issues

### ISSUE THREAD

**Issue by alexander-poon** [tnedu/accountability#10]
**Ready Grad**

Issue: There are students in the ready grad file associated with schools that closed in 2016, 2017, etc. The cause is that students withdrew from those schools before the schools subsequently closed.

Resolution: Drop all students associated these closed schools in the school level ready grad file, but keep them in the district level files.

**MSAA**

Issue: In the MSAA file, districts 961 (Alvin C York), 963 (School for Blind), 964 (School for Deaf), and 970 (DCS) are incorrectly showing the same system/school number.

Resolution: 961 and 963 have only one school so we can impute the correct school number. Handle 964 and 970 on appeals by letting these districts tell us which school the records should be associated with.

 

**WIDA**

Issue: There are 15 records associated with Raleigh-Egypt Middle School (792/2596). This school closed as of summer 2016, though is reopening with a different school number in the upcoming school year. These students were not pre-ID’d with the 792/2596 system/school number so it is not clear why these students are showing under 792/2596.

Latest: Freddie is reaching out to WIDA to see how these students wound up with the 792/2596 school number.

**Accountability System/School**

Issue: To identify accountability system and school, we take the student level attendance file, check for students who were enrolled in more than one school, then identify the school at which they were enrolled for the most ISP days. If this number of days represents a majority of days in that school’s instructional calendar, use this school as the student’s accountability system/school. However, if we were to check the district where a student spent the most number of school days, the district might not align with the school. 

Proposed solution: Do nothing, and leave to appeals. There are 29 instances where this happens.

**CDF Issues**
- [X] 3000 records from raw score file are missing in the CDF.
~- [ ] SNT status is showing only 0 or 1.~
> Leaving as is. We also overwrote the failed attemptedness flag (`ri_status == 6`) for absent students (`reason_not_tested == 1`).
- [X] Content areas were changed (i.e., SCI = social studies).
~- [ ] Can't confirm that attemptedness rules are applied correctly.~
> Ongoing. Leap of faith.
- [X] 4 records from 7/1 CDF were not in 7/3 CDF.
 - [X] Norris Elementary School in Anderson County (10/70) was missing 30+ grade 3 records. These were marked with a `ri_status` of 1 (Adult Potential Breach of Security), but they also had answers bubbled. As such, Questar presumably scored them but did not report a score in the CDF. We will leave as is and deny any appeals regarding these students. Anderson County can submit a report resolution. 

**Absenteeism File Issues**
- [x] Native American subgroup was counting African American students instead.
- [x] Service Enrollments were included in the attendance pull

**Assessment File Issues**
- [x] Students with missing demographics are also missing `enrolled_50_pct_school` and `enrolled_50_pct_district` values.
- [x] Some students in the WIDA ACCESS file have either a `NA` or `0` value for the `el` variable (should be `1`).
- [x] Should `acct_system` and `acct_school` values be blank for students who have values of `N` for `enrolled_50_pct_district` and `enrolled_50_pct_school`, respectively?

**Comment by alexander-poon** [comment]
> Should `acct_system` and `acct_school` values be blank for students who have values of `N` for `enrolled_50_pct_district` and `enrolled_50_pct_school`, respectively?

These are dealt with in the process of creating the accountability files here:

https://github.com/tnedu/accountability/blob/master/2019-accountability/school/school_accountability_file.R#L18

and here:

https://github.com/tnedu/accountability/blob/master/2019-accountability/district/district_accountability_file.R#L40

respectively.

**Comment by evan-kramer** [comment]
>WIDA

>Issue: There are 15 records associated with Raleigh-Egypt Middle School (792/2596). This school closed as of summer 2016, though is reopening with a different school number in the upcoming school year. These students were not pre-ID’d with the 792/2596 system/school number so it is not clear why these students are showing under 792/2596.

>Latest: Freddie is reaching out to WIDA to see how these students wound up with the 792/2596 school number.

Shelby County manually provisioned these students to the wrong school. Alex sent Freddie names and USIDs for affected students; Freddie will contact Brant in Shelby County. We will then have to reassign, re-run, re-match, and re-upload WIDA ACCESS files.

**Comment by evan-kramer** [comment]
@alexander-poon Any word from Freddie on reassigning these students? 
@amarsee Thanks for finding the issue of students in WIDA ACCESS file not being identified as `el == 1` in the student-level file. I'll document in the issue above. I propose re-releasing updated student-level files that include `teacher_of_record` variable and updated `el` variable.

**Comment by alexander-poon** [comment]
Haven't heard from Freddie yet.

**Comment by evan-kramer** [comment]
On Thursday the advisory group brought up a number of issues to resolve when we release files early next week:

__Required__:
- [ ] District files currently don't include students with `acct_system` values of their district ID (i.e., it filters/splits based only on the `system` variable. We'll need to adjust this split on Monday.
- [ ] File layouts differ from the actual files in a number of places. We'll need to reconcile these.
- [ ] Teacher of record was missing from the files. We'll need to add this in. 

__To Discuss__:
- [ ] Folks asked for a "comparison to state" field for the assessment files that would indicate how their performance in a given grade, test, subject, subgroup compared to the state.
- [ ] Folks also asked for grade, test, subject, subgroup AMOs in the same file. This felt less reasonable, but still doable.
- [ ] Absenteeism files did not have prior year data (whereas assessment files have 2017-2019. We should consider adding.
- [ ] Participants asked for a summary file or sheet that would distill high-level findings of assessment files. We would need to think about how to do this appropriately/adequately.
- [ ] People asked for the accountability files to include percentiles for TSI identification purposes (i.e., even for those with non-identified subgroups to know how close they were to identification) and for success rate percentiles as well.

**Comment by alexander-poon** [comment]
> Should `acct_system` and `acct_school` values be blank for students who have values of `N` for `enrolled_50_pct_district` and `enrolled_50_pct_school`, respectively?

As I understand it, this will not work because `enrolled_50_pct` refers to the assessment district/school. Students who spent < 50% of the year in their assessment school but > 50% of the year elsewhere will have `N` under `enrolled_50_pct` but are specifically the students we are trying to reassign with `acct_system` and `acct_school`. Someone reality check me on this?

**Comment by evan-kramer** [comment]
@alexander-poon Good flag; we'll leave as is.

**Comment by amarsee** [comment]
Status right now:

- We are matching on District Designations
- Almost matching on school_grading_metrics. There are some subgroups of schools getting left out in the joins if they don't have an achievement subgroup.
- We seem close on school_grading_grades. I haven't had a chance to fully look into yet.
- I'll add matching tests for the school grading to the tests repo and push to github in my branch

**Comment by amarsee** [comment]
There are scenarios where the USID from the CDF is incorrect but it matches with a real USID from a student enrolled in a different district
