### ISSUE TITLE
Accountability file releases

### ISSUE THREAD

**Issue by evan-kramer** [tnedu/accountability#11]
__Match__: 
- [x] School accountability file
- [x] School grading metrics
- [x] School grading grades
- [x] Priority exit
- [x] ATSI 
- [x] School heat maps
- [x] District accountability file
- [x] District designations
- [x] District heat maps

**Comment by alexander-poon** [comment]
Four 985 schools are not showing as priority/CSI. They were designation ineligible last year which is why they weren't identified as priority/CSI last year. Question is whether they should automatically become CSI now that they aren't ineligible.
