### ISSUE TITLE
Accountability Protocol Thoughts for Next Year

### ISSUE THREAD

**Issue by amarsee** [tnedu/accountability#12]
Protocol Ideas Moving Forward:

- [ ] Should Super Subgroup be substituted at the indicator level if a school has no subgroups for the indicator, but has a Super Subgroup score
- [ ] Clarification on the 60, 40 weighting across indicators first

Update 1/13: Leaving Super Subgroup business rule as is. 60/40 has been clarified in protocol.

**Comment by alexander-poon** [comment]
Neely's Bend (priority school) met a 2018 10th percentile based on a success rate including Math, ELA, Science. We recalculated their 2018 success rate for AMO targets based on only Math and ELA, and used the recalculated 2018 success rate to determine priority exit status. 

To revisit and notate in protocol: if subjects change from year to year, do we allow schools to exit based on one or either version of success rates?

**Comment by alexander-poon** [comment]
For absenteeism, EIS data reports is reflecting the withdrawal date as an absence. We need to update our query to not do this.

**Comment by alexander-poon** [comment]
Follow up with KB about updated WIDA exit criteria.

**Comment by alexander-poon** [comment]
Consider 50 percent enrolled by fall/spring block.
